<?php
// module/Album/view/album/album/index.phtml:

$title = $this->translate('application_album_title');
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('album', ['action' => 'add'], true) ?>"><?= $this->translate('application_album_new') ?></a>
</p>

<table class="table">
<tr>
    <th><?= $this->translate('Album title') ?></th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $album) : // <-- change here! ?>
    <tr>
        <td><?= $this->escapeHtml($album->title) ?></td>
        <td><?= $this->escapeHtml($album->artist) ?></td>
        <td>
            <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id], true) ?>"><?= $this->translate('application_album_edit') ?></a>
            <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id], true) ?>"><?= $this->translate('application_album_delete')?></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>

<?php
// In module/Album/view/album/album/index.phtml:
// Add at the end of the file after the table:
?>
<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'album']
) ?>
