<?php
// module/Book/view/book/book/index.phtml:

$title = $this->translate('application_book_title');
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('book', ['action' => 'add'], true) ?>"><?= $this->translate('application_book_new') ?></a>
</p>

<table class="table">
<tr>
    <th><?= $this->translate('Title')?></th>
    <th>Autor</th>
	<th>Land</th> <!--Land eingefügt -->
    <th>&nbsp;</th>
</tr>
 <?php foreach ($this->paginator as $book) : // <-- change here! ?>
    <tr>
        <td><?= $this->escapeHtml($book->title) ?></td>
        <td><?= $this->escapeHtml($book->autor) ?></td>
		<td><?= $this->escapeHtml($book->land) ?></td>
        <td><!--Verlinkungen auf index Seite -->
            <a href="<?= $this->url('book', ['action' => 'edit', 'id' => $book->id], true) ?>"><?= $this->translate('application_book_edit') ?></a>
            <a href="<?= $this->url('book', ['action' => 'delete', 'id' => $book->id], true) ?>"><?= $this->translate('application_book_delete')?></a>
        </td>
    </tr>
<?php endforeach; ?>
</table>

<?php
// In module/Book/view/book/book/index.phtml:
// Add at the end of the file after the table:
?>
<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'book']
) ?>
